Models/Page.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace webshopgaragemanager.Models
{
    public class Page
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        public string Content { get; set; }
        public int Sorting { get; set; }
    }
}

Pages/CheckOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DTOLibrary;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using webshopgaragemanager.DataAccess;

namespace webshopgaragemanager.Pages
{
    public class CheckOutModel : PageModel
    {
        private readonly IDataAccess _dataAccess;
        
        public CheckOutModel(IDataAccess dataAccess)
        {
            summa = 0;
            foreach (var cartitem in shoppingCartModel.ShoppingCartItem)
            {
                summa += cartitem.price;
            }
        }
        
        public static int summa;

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace webshopgaragemanager.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using DTOLibrary;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using webshopgaragemanager.DataAccess;

namespace webshopgaragemanager.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IDataAccess _dataAccess;
        public IndexModel(IDataAccess dataAccess)
        {
            _dataAccess = dataAccess;
            Item = (List<ItemDTO>)_dataAccess.GetAllitems();
        }
        public List<ItemDTO> Item { get; set; }     
        public static string SearchTerm = "";
        public static int HighestTerm = 0;
        public void OnGet()
        {
        }
        public void OnPost()
        {
        }
        public void OnPostAddItem()
        {
            var item_url = Request.Form["item_url"];
            var item_name = Request.Form["item_name"];
            var item_price = Request.Form["item_price"];
            var item_itemid = Request.Form["item_itemid"];
            var MyObj = new ItemDTO();
            MyObj.imgUrl = item_url;
            MyObj.name = item_name;
            MyObj.price = Convert.ToInt32(item_price);
            MyObj.itemid = Convert.ToInt32(item_itemid);
            
            shoppingCartModel.ShoppingCartItem.Add(MyObj);
            var MyObjTotalPrice = new ShoppingCartDTO();
            MyObjTotalPrice.CheckOutPrice += MyObj.price;
            MyObjTotalPrice.CheckOutPriceTotal = MyObjTotalPrice.CheckOutPrice;
        }

        public void OnPostSearchItem()
        {
            SearchTerm = Request.Form["fname"];
        }

        public void OnPostHighest()
        {
            HighestTerm = Convert.ToInt32(Request.Form["Highest"]);
        }
        
        [BindProperty]
        public string SortTerm { get; set; }
        public IActionResult OnPostSort()
        {
            OnGet();
            switch (SortTerm)
            {
                case "Name":
                    Item = Item.OrderBy(o => o.name).ToList();
                    break;

                case "LPrice":
                    Item = Item.OrderBy(o => o.price).ToList();
                    break;

                case "HPrice":
                    Item = Item.OrderByDescending(o => o.price).ToList();
                    break;
            }
            return Page();
        }
    }
}

Pages/shoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DTOLibrary;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using webshopgaragemanager.DataAccess;

namespace webshopgaragemanager.Pages
{
    public class shoppingCartModel : PageModel
    {
        private readonly IDataAccess _dataAccess;
        public shoppingCartModel(IDataAccess dataAccess)
        {
            _dataAccess = dataAccess;
            Customer = (List<CustomerDTO>)_dataAccess.GetAllCustomers();
            CustomerNameAndAddress = (List<ChosenCustomerItemDTO>)_dataAccess.GetAllChosenCustomerItemnames();
        }
        public static List<ItemDTO> ShoppingCartItem = new List<ItemDTO>();
        public static List<CustomerDTO> Customer { get; set; }
        public static List<ChosenCustomerItemDTO> CustomerNameAndAddress { get; set; }

        public static bool IsPaid;

        public static int Key;

        public IActionResult OnPost()
        {
            Key = Convert.ToInt32(Request.Form["item_name1"]);
            IsPaid = true;
            return RedirectToPage("./CheckOut");
        }
    }
}

Pages/CheckOut.cshtml
@page
@model webshopgaragemanager.Pages.CheckOutModel
@{
}

<div class="card-deck">
    <h1>RECEIPT:</h1>
</div>

@foreach (var PriceCheckOut in shoppingCartModel.ShoppingCartItem)
{
    <div class="card" style="width: auto;">
        <p class="card-text">@PriceCheckOut.name</p>
        <p class="card-text">$@PriceCheckOut.price</p>

    </div>
}

<p class="card-text">Total price (in dollar): $@CheckOutModel.summa</p>
<p class="card-text">Name: @shoppingCartModel.Customer[shoppingCartModel.Key].name</p>
<p class="card-text">Address: @shoppingCartModel.Customer[shoppingCartModel.Key].address</p>


@if (shoppingCartModel.IsPaid)
{
    <p class="card-text"><b>PAID!</b></p>
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<style>
    #myColor {
        background-color: red;
    }
</style>

<div class="card-deck">
    <form asp-page-handler="SearchItem">
        <label for="fname">Search Item Name:</label>
        <input type="text" id="fname" name="fname" value="@IndexModel.SearchTerm"><br><br>
        <input type="submit" value="Submit">
    </form>
    @foreach (var item in Model.Item)
    {
        @if (item.name.ToLower().Contains(IndexModel.SearchTerm.ToLower()))
        {
            <div class="card" style="width: auto;">
                <form asp-page-handler="AddItem">
                    <img class="card-img-top" width="100" height="100" src="@item.imgUrl" alt="Card image cap">
                    <p class="card-text">@item.name</p>
                    <p class="card-text">$@item.price</p>
                    <p class="card-text">@item.itemid</p>
                    <input type="hidden" name="item_url" value="@item.imgUrl" />
                    <input type="hidden" name="item_name" value="@item.name" />
                    <input type="hidden" name="item_price" value="@item.price" />
                    <input type="hidden" name="item_itemid" value="@item.itemid" />
                    <input type="submit" value="Add to Cart" />
                </form>
                <div class="card-body">
                </div>
            </div>
        }
    }
</div>

<form asp-page-handler="Sort" class="d-flex align-content-center">
    <label class="mr-2">Sortera: </label>
    <select asp-for="SortTerm" class="h-100 d-flex" onchange="this.form.submit()" style="padding: 5px;">
        <option value="Name">Namn</option>
        <option value="LPrice">Lägsta Pris</option>
        <option value="HPrice">Högsta Pris</option>
    </select>
</form>

<div class="card-deck">
    <form asp-page-handler="Highest">
        <label for="Highest">What's your Budget<br/>Enter highest Price:</label>
        <input type="text" id="Highest" name="Highest"><br><br>
        <input type="submit" value="Submit">
    </form>
    @foreach (var item in Model.Item)
    {
        @if (item.price <= IndexModel.HighestTerm)
        {
            <div class="card" style="width: auto;">
                <form asp-page-handler="AddItem">
                    <img class="card-img-top" width="100" height="100" src="@item.imgUrl" alt="Card image cap">
                    <p class="card-text">@item.name</p>
                    <p class="card-text">$@item.price</p>
                    <p class="card-text">@item.itemid</p>
                    <input type="hidden" name="item_url" value="@item.imgUrl" />
                    <input type="hidden" name="item_name" value="@item.name" />
                    <input type="hidden" name="item_price" value="@item.price" />
                    <input type="hidden" name="item_itemid" value="@item.itemid" />
                    <input type="submit" value="Add to Cart" />
                </form>
                <div class="card-body">
                </div>
            </div>
        }
    }
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<style>
    #myColor {
        background-color: red;
    }
</style>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webshopgaragemanager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header id="myColor">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">webshopgaragemanager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/ShoppingCart">ShoppingCart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>
    <footer class="border-top footer text-muted" id="myColor">
        <div class="container">
            &copy; 2021 - webshopgaragemanager - <a asp-area="" asp-page="/ShoppingCart">ShoppingCart</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/shoppingCart.cshtml
@page
@model webshopgaragemanager.Pages.shoppingCartModel
@{
}

<div class="card-deck">
    <h1>Shopping cart:</h1>
    <table>
        @foreach (var item in shoppingCartModel.ShoppingCartItem)
        {
            <tr>
                <td>
                    <img class="card-img-top" src="@item.imgUrl" height="100" alt="Card image cap">
                    <p class="card-text">Name: @item.name</p>
                    <p class="card-text">Price (In dollar): $@item.price</p>
                    <p class="card-text">Item Id: @item.itemid</p>
                    <div class="card-body"></div>
                </td>
            </tr>
        }
    </table>
</div>

<form method="post">
    <label for="cars">Choose name and address:</label>
    <select name="item_name1" id="item_name1">
        @for (int i = 0; i < shoppingCartModel.Customer.Count; i++)
        {
            <option value="@i">@shoppingCartModel.Customer[i].name</option>

        }

    </select>
    <br><br>
    <input type="submit" value="Buy and kvitto">
</form>